var APP_NAME = "PhazonOS";
var APP_VERSION = "0.01";
var CPU_CLOCK_INTERVAL = 100;
var TIMER_IRQ = 0;
var KEYBOARD_IRQ = 1;
var MEMORY_SIZE = 256;
var _CPU;
var _OSclock = 0;
var _Mode = 0;
var _MemoryManager;
var _CurrentPCB;
var _Canvas;
var _DrawingContext;
var _DefaultFontFamily = "sans";
var _DefaultFontSize = 13;
var _FontHeightMargin = 4;
var _Trace = true;
var _Kernel;
var _KernelInterruptQueue;
var _KernelInputQueue = null;
var _KernelBuffers = null;
var _StdIn;
var _StdOut;
var _Console;
var _OsShell;
var _SarcasticMode = false;
var _krnKeyboardDriver;
var _hardwareClockID = null;
var Glados = null;
var _GLaDOS = null;
var onDocumentLoad = function () {
    var currentDate = new Date();
    TSOS.Control.hostInit();
    setInterval(function () {
        document.getElementById("dateTimeLabel").innerHTML = "Time: " + currentDate.getHours() + ":" + currentDate.getMinutes() + " " + currentDate.toLocaleDateString();
    }, 1000);
};
