var APP_NAME = "PhazonOS";
var APP_VERSION = "6.6";
var CPU_CLOCK_INTERVAL = 100;
var TIMER_IRQ = 0;
var KEYBOARD_IRQ = 1;
var CONTEXT_IRQ = 2;
var MEMORY_SIZE = 256;
var MEMORY_PARTITIONS = 3;
var TOTAL_MEMORY_SIZE = MEMORY_PARTITIONS * MEMORY_SIZE;
var TRACKS = 4;
var SECTORS = 8;
var BLOCKS = 8;
var BLOCK_SIZE = 64;
var NEW = 0;
var RUNNING = 1;
var WAITING = 2;
var READY = 3;
var TERMINATED = 4;
var RR = 0;
var FCFS = 1;
var PRTY = 2;
var _CPU;
var _HardDrive;
var _OSclock = 0;
var _Mode = 0;
var _MemoryManager;
var _CurrentPCB = null;
var _ReadyQueue;
var _ResidentList;
var _CpuScheduler;
var _TimeQuantum = 6;
var _SchedMode = RR;
var _Canvas;
var _DrawingContext;
var _DefaultFontFamily = "sans";
var _DefaultFontSize = 13;
var _FontHeightMargin = 4;
var _Trace = true;
var _Status = "";
var _Kernel;
var _KernelInterruptQueue;
var _KernelInputQueue = null;
var _KernelBuffers = null;
var _StdIn;
var _StdOut;
var _Console;
var _OsShell;
var _SarcasticMode = false;
var _SingleStepMode = false;
var _krnKeyboardDriver;
var _krnHardDriveDriver;
var _hardwareClockID = null;
var Glados = null;
var _GLaDOS = null;
var onDocumentLoad = function () {
    TSOS.Control.hostInit();
};
